name: dev-oracle

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEV_SERVER_SSH_KEY }}

      # 3. Deploy to server
      - name: Deploy to Development
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEV_SERVER_USER }}@${{ secrets.DEV_SERVER_IP }} << 'EOF'
            cd /opt/development || exit
            git init
            git remote add origin git@github.com:vem882/CI_CD.git || true
            git fetch origin dev
            git reset --hard origin/dev
            node app.js
          EOF
